"""
Kinship QA generator. Produces letter-only MC train/test parquets.

Categories (per person, ~200-300 questions total):
  Cat 1  direct 1-hop  (single):  father, mother, husband, wife
  Cat 1m direct 1-hop  (multi):   sons, daughters
  Cat 1w whose-style 1-hop:       "Whose {child|parent|spouse role} is X?"
  Cat 2  direct multi-hop (single): grandfather, grandmother
  Cat 2m direct multi-hop (multi):  brothers, sisters, uncles, aunts,
                                    grandsons, granddaughters, cousins
                                    (nephew/niece intentionally removed)
  Cat 3  counting (5 templates):  children, sons, daughters, siblings,
                                  grandchildren
  Cat 4  verification (3-option Y/N/Unknown):
         "Is A B's {rel}?" — mix true/false per (B, rel)
  Cat 5  existence (3-option Y/N/Unknown):
         "Does X have any {rel_plural}?"
  Cat 6  disambig (5-option):
         "Name one of X's {rel_plural}." Correct = lex-first valid;
         distractors NOT in valid set.

Train/test split (--split-mode): "question" (default) = random hold-out of 20%
of questions; "person" = hold out whole people (test asks only about unseen
people → structural generalization, REPORT §3.3).

Assistant content = letter only (no reasoning). Reasoning is generated by
the model at eval time; loss masking is applied at training time to keep
loss only on the letter token.

Usage:
    python examples/graph/graph_qagen.py
    python examples/graph/graph_qagen.py --tree variants/alex/family_tree.json --out-dir variants/alex
    python examples/graph/graph_qagen.py --n-verif-per-rel 14 --test-frac 0.2
"""
from __future__ import annotations
import argparse
import json
import random
from pathlib import Path

from cartridges.structs import Conversation, write_conversations
from examples.graph.data_gen.family_tree import FamilyTree, hops_for

# ── Template registries ─────────────────────────────────────────────────────
CAT1_SINGLE = [
    ("father",  "Who is {name}'s father?"),
    ("mother",  "Who is {name}'s mother?"),
    ("husband", "Who is {name}'s husband?"),
    ("wife",    "Who is {name}'s wife?"),
]
CAT1_MULTI = [
    ("son",      "Who are {name}'s sons?"),
    ("daughter", "Who are {name}'s daughters?"),
]
# Whose-style 1-hop: ask the inverse direction with a different surface form.
# For each (child_rel, parent_rel) the answers to "Whose {child_rel} is X?"
# are exactly lookup[X][parent_rel].
CAT1_WHOSE = [
    # asking for parents of X (X is the {role} of whom?)
    ("son",      "father",  "Whose son is {name}?"),
    ("son",      "mother",  "Whose son is {name}?"),
    ("daughter", "father",  "Whose daughter is {name}?"),
    ("daughter", "mother",  "Whose daughter is {name}?"),
    # asking for children of X
    ("father",   "son",      "Whose father is {name}?"),
    ("father",   "daughter", "Whose father is {name}?"),
    ("mother",   "son",      "Whose mother is {name}?"),
    ("mother",   "daughter", "Whose mother is {name}?"),
    # asking for spouse of X
    ("husband",  "wife",     "Whose husband is {name}?"),
    ("wife",     "husband",  "Whose wife is {name}?"),
]
CAT2_SINGLE = [
    ("grandfather", "Who is {name}'s grandfather?"),
    ("grandmother", "Who is {name}'s grandmother?"),
]
CAT2_MULTI = [
    ("brother",       "Who are {name}'s brothers?"),
    ("sister",        "Who are {name}'s sisters?"),
    ("uncle",         "Who are {name}'s uncles?"),
    ("aunt",          "Who are {name}'s aunts?"),
    ("grandson",      "Who are {name}'s grandsons?"),
    ("granddaughter", "Who are {name}'s granddaughters?"),
    ("cousin",        "Who are {name}'s cousins?"),
]
CAT3 = [
    (["son", "daughter"],            "How many children does {name} have?"),
    (["son"],                        "How many sons does {name} have?"),
    (["daughter"],                   "How many daughters does {name} have?"),
    (["brother", "sister"],          "How many siblings does {name} have?"),
    (["grandson", "granddaughter"],  "How many grandchildren does {name} have?"),
]

# Relations to verify in Cat 4 (Is A B's rel?). Covers all answer-shape kinds.
VERIFICATION_RELS = [
    "father", "mother", "husband", "wife",
    "son", "daughter",
    "brother", "sister",
    "uncle", "aunt",
    "grandfather", "grandmother",
    "grandson", "granddaughter",
    "cousin",
]

# Multi-answer rels used by Cat 5 (existence) and Cat 6 (disambig).
EXISTENCE_RELS = [
    ("son",          "sons"),
    ("daughter",     "daughters"),
    ("brother",      "brothers"),
    ("sister",       "sisters"),
    ("uncle",        "uncles"),
    ("aunt",         "aunts"),
    ("cousin",       "cousins"),
    ("grandson",     "grandsons"),
    ("granddaughter","granddaughters"),
]

OPTION_LETTERS_5 = "ABCDE"
OPTION_LETTERS_3 = "ABC"


# ── Graph BFS lookup ────────────────────────────────────────────────────────
def build_rel_lookup(tree: FamilyTree) -> dict[str, dict[str, list[str]]]:
    """lookup[X][rel] = [people who ARE X's rel]."""
    names = [p["name"] for p in tree.people]
    out: dict[str, dict[str, list[str]]] = {n: {} for n in names}
    for a in names:
        for b in names:
            if a == b:
                continue
            res = tree.find_path_reasoning(a, b)
            if not res:
                continue
            _, rel, _ = res
            if rel == "distant relative":
                continue
            out[b].setdefault(rel, [])
            if a not in out[b][rel]:
                out[b][rel].append(a)
    return out


def format_answer(names: list[str]) -> str:
    if not names:
        return "None."
    return ", ".join(sorted(names)) + "."


# ── Cat 1/1m/1w/2/2m: deterministic per (person, template) ──────────────────
def _qa_record(question, answer, category, rel, person, **extra):
    # category is coerced to string so parquet schema stays consistent across
    # subcategories like "1m" / "1w" / "2m". `hops` = relation hop-class for
    # per-hop eval (see family_tree.hops_for).
    return {
        "question": question, "answer": answer, "category": str(category),
        "rel": rel, "person": person, "hops": hops_for(category, rel), **extra,
    }


def gen_cat1_2_3(tree: FamilyTree, lookup: dict) -> list[dict]:
    out: list[dict] = []
    gender_of = {p["name"]: p["gender"] for p in tree.people}
    for p in tree.people:
        name = p["name"]
        for rel, tmpl in CAT1_SINGLE:
            # gate spouse questions by gender (Steven has no husband)
            if rel == "husband" and gender_of[name] != "female":
                continue
            if rel == "wife" and gender_of[name] != "male":
                continue
            out.append(_qa_record(
                tmpl.format(name=name),
                format_answer(lookup[name].get(rel, [])),
                1, rel, name,
            ))
        for rel, tmpl in CAT1_MULTI:
            out.append(_qa_record(
                tmpl.format(name=name),
                format_answer(lookup[name].get(rel, [])),
                "1m", rel, name,
            ))
        for child_rel, ans_rel, tmpl in CAT1_WHOSE:
            # only emit if X's gender/role makes sense (e.g. "Whose son is X?"
            # requires X is male — if no parents of X exist in lookup[name],
            # we drop the question)
            answers = lookup[name].get(ans_rel, [])
            # filter by gender consistency of X:
            gender = next((q["gender"] for q in tree.people if q["name"] == name), None)
            if child_rel in ("son", "father", "husband") and gender != "male":
                continue
            if child_rel in ("daughter", "mother", "wife") and gender != "female":
                continue
            out.append(_qa_record(
                tmpl.format(name=name),
                format_answer(answers),
                "1w", f"whose_{child_rel}_{ans_rel}", name,
            ))
        for rel, tmpl in CAT2_SINGLE:
            out.append(_qa_record(
                tmpl.format(name=name),
                format_answer(lookup[name].get(rel, [])),
                2, rel, name,
            ))
        for rel, tmpl in CAT2_MULTI:
            out.append(_qa_record(
                tmpl.format(name=name),
                format_answer(lookup[name].get(rel, [])),
                "2m", rel, name,
            ))
        for rel_list, tmpl in CAT3:
            count = sum(len(lookup[name].get(r, [])) for r in rel_list)
            out.append(_qa_record(
                tmpl.format(name=name),
                f"{count}.",
                3, "+".join(rel_list), name,
            ))
    return out


# ── Cat 4: verification "Is A B's rel?" ─────────────────────────────────────
def gen_cat4_verification(
    tree: FamilyTree, lookup: dict, rng: random.Random,
    n_per_person_rel: int = 12, true_share: float = 0.33,
) -> list[dict]:
    """For each (X, rel) emit up to `n_per_person_rel` (A, X, rel) tuples.
    Mix true/false; pad with false when not enough true candidates.
    """
    all_names = [p["name"] for p in tree.people]
    out: list[dict] = []
    n_true_target = max(1, int(n_per_person_rel * true_share))

    for x in all_names:
        for rel in VERIFICATION_RELS:
            true_pool = list(lookup[x].get(rel, []))
            false_pool = [n for n in all_names if n != x and n not in true_pool]
            rng.shuffle(true_pool); rng.shuffle(false_pool)

            n_true  = min(n_true_target, len(true_pool))
            n_false = min(n_per_person_rel - n_true, len(false_pool))

            for a in true_pool[:n_true]:
                out.append(_qa_record(
                    f"Is {a} {x}'s {rel}?", "Yes.", 4, f"verify_{rel}", x,
                    verify_a=a, verify_b=x, verify_truth=True,
                ))
            for a in false_pool[:n_false]:
                out.append(_qa_record(
                    f"Is {a} {x}'s {rel}?", "No.", 4, f"verify_{rel}", x,
                    verify_a=a, verify_b=x, verify_truth=False,
                ))
    return out


# ── Cat 5: existence "Does X have any rel_plural?" ──────────────────────────
def gen_cat5_existence(tree: FamilyTree, lookup: dict) -> list[dict]:
    out: list[dict] = []
    for p in tree.people:
        name = p["name"]
        for rel, plural in EXISTENCE_RELS:
            has_any = bool(lookup[name].get(rel, []))
            out.append(_qa_record(
                f"Does {name} have any {plural}?",
                "Yes." if has_any else "No.",
                5, f"exist_{rel}", name,
            ))
    return out


# ── Cat 6: disambig "Name one of X's rel_plural" ────────────────────────────
def gen_cat6_disambig(tree: FamilyTree, lookup: dict) -> list[dict]:
    out: list[dict] = []
    for p in tree.people:
        name = p["name"]
        for rel, plural in EXISTENCE_RELS:
            valid = sorted(lookup[name].get(rel, []))
            if len(valid) < 2:  # disambig only meaningful when ≥2 valid
                continue
            chosen = valid[0]  # deterministic: alphabetically first
            out.append(_qa_record(
                f"Name one of {name}'s {plural}.",
                f"{chosen}.",
                6, f"disambig_{rel}", name,
                disambig_set=valid,
            ))
    return out


# ── Train/test split ─────────────────────────────────────────────────────────
def split_by_person(
    tree: FamilyTree, qa: list[dict], test_frac: float, seed: int,
) -> tuple[list[dict], list[dict], list[str], list[str]]:
    """Hold out whole PEOPLE: test questions are about people never seen in
    train → measures structural generalization (REPORT §3.3)."""
    rng = random.Random(seed)
    names = [p["name"] for p in tree.people]
    rng.shuffle(names)
    n_test = max(1, int(len(names) * test_frac))
    test_people = set(names[:n_test])
    train_people = set(names[n_test:])
    train_qa = [q for q in qa if q["person"] in train_people]
    test_qa  = [q for q in qa if q["person"] in test_people]
    return train_qa, test_qa, sorted(train_people), sorted(test_people)


def split_by_question(
    qa: list[dict], test_frac: float, seed: int,
) -> tuple[list[dict], list[dict]]:
    """Random hold-out of QUESTIONS regardless of person, STRATIFIED by category
    (each category contributes test_frac to test) so small categories stay
    represented in both splits. Test may ask about people also seen in train."""
    rng = random.Random(seed)
    by_cat: dict[str, list[dict]] = {}
    for q in qa:
        by_cat.setdefault(q["category"], []).append(q)
    train_qa, test_qa = [], []
    for cat in sorted(by_cat):
        items = by_cat[cat][:]
        rng.shuffle(items)
        n_test = max(1, int(len(items) * test_frac)) if len(items) > 1 else 0
        test_qa.extend(items[:n_test])
        train_qa.extend(items[n_test:])
    rng.shuffle(train_qa)
    rng.shuffle(test_qa)
    return train_qa, test_qa


# ── Category mixture (rebalance) ───────────────────────────────────────────────
# Target shares per category. Reasoning categories (1/1m/1w/2/2m/3/6) keep ~their
# natural proportions; verification(4)+existence(5) are capped to ~25% combined
# (raw data is 88% verify+exist — see REPORT §13.2). Categories absent here are
# DROPPED, so this doubles as category selection. Shares need not sum to 1.
MIX_DEFAULT: dict[str, float] = {
    "1": 0.09, "1m": 0.06, "1w": 0.15, "2": 0.06, "2m": 0.21, "3": 0.15, "6": 0.03,
    "4": 0.18, "5": 0.07,
}


def rebalance(qa: list[dict], mix: dict[str, float], seed: int) -> list[dict]:
    """Downsample categories to match target shares (no upsampling).

    Picks the largest total T s.t. share_c * T <= available_c for every category
    in `mix`, then samples round(share_c * T) per category. Categories not in
    `mix` are dropped. Deterministic given seed.
    """
    rng = random.Random(seed)
    by_cat: dict[str, list[dict]] = {}
    for q in qa:
        by_cat.setdefault(q["category"], []).append(q)

    present = {c: s for c, s in mix.items() if s > 0 and by_cat.get(c)}
    if not present:
        return qa
    total = min(len(by_cat[c]) / s for c, s in present.items())

    out: list[dict] = []
    for c, s in present.items():
        pool = by_cat[c]
        n = min(len(pool), round(s * total))
        out.extend(pool if n >= len(pool) else rng.sample(pool, n))
    rng.shuffle(out)
    return out


# ── MC option construction ─────────────────────────────────────────────────
def _mc_seed(q: dict) -> int:
    extra = q.get("verify_a", "") + str(q.get("verify_b", ""))
    return abs(hash(("mc", q["person"], q["rel"], q["question"], extra))) & 0xFFFFFFFF


def _mc_yes_no_unknown(answer: str, seed: int) -> tuple[list[str], int]:
    rng = random.Random(seed)
    opts = ["Yes.", "No.", "Unknown."]
    rng.shuffle(opts)
    return opts, opts.index(answer)


def _mc_counting(answer: str, seed: int) -> tuple[list[str], int]:
    rng = random.Random(seed)
    n = int(answer.rstrip("."))
    upper = max(n + 5, 8)
    pool = [k for k in range(0, upper) if k != n]
    rng.shuffle(pool)
    opts = [f"{k}." for k in pool[:4]] + [answer]
    rng.shuffle(opts)
    return opts, opts.index(answer)


def _mc_name_single(answer: str, all_names: list[str], seed: int,
                    forbid_in_options: set[str] | None = None) -> tuple[list[str], int]:
    rng = random.Random(seed)
    if answer == "None.":
        forbid = forbid_in_options or set()
        pool = [n for n in all_names if n not in forbid]
        picks = rng.sample(pool, min(4, len(pool)))
        opts = [f"{p}." for p in picks] + [answer]
    else:
        correct_name = answer.rstrip(".")
        forbid = forbid_in_options or set()
        forbid = forbid | {correct_name}
        pool = [n for n in all_names if n not in forbid]
        picks = rng.sample(pool, min(3, len(pool)))
        opts = [f"{p}." for p in picks] + ["None."] + [answer]
        opts = opts[:5]  # safety
    rng.shuffle(opts)
    return opts, opts.index(answer)


def _mc_name_multi(answer: str, all_names: list[str], seed: int) -> tuple[list[str], int]:
    rng = random.Random(seed)
    if answer == "None.":
        picks = rng.sample(all_names, min(4, len(all_names)))
        opts = [f"{p}." for p in picks] + [answer]
        rng.shuffle(opts)
        return opts, opts.index(answer)

    names_in = sorted(n.strip() for n in answer.rstrip(".").split(","))
    pool_other = [n for n in all_names if n not in names_in]

    cand: list[list[str]] = []
    if len(names_in) > 1:
        cand.append(names_in[:-1])
    if pool_other:
        cand.append(sorted(names_in + [rng.choice(pool_other)]))
        cand.append(sorted(names_in[:-1] + [rng.choice(pool_other)]))
        cand.append(sorted(rng.sample(pool_other, min(len(names_in), len(pool_other)))))
    cand.append([])  # None.

    seen = {tuple(names_in)}
    distractors: list[str] = []
    for c in cand:
        t = tuple(c)
        if t in seen:
            continue
        seen.add(t)
        distractors.append(", ".join(c) + "." if c else "None.")
        if len(distractors) == 4:
            break
    while len(distractors) < 4 and pool_other:
        pick = rng.choice(pool_other)
        s = f"{pick}."
        if s not in distractors and s != answer:
            distractors.append(s)
    while len(distractors) < 4:
        distractors.append("None.")

    opts = distractors[:4] + [answer]
    rng.shuffle(opts)
    return opts, opts.index(answer)


def build_mc_record(q: dict, all_names: list[str]) -> dict:
    seed = _mc_seed(q)
    ans = q["answer"]
    cat = q["category"]

    # NOTE: category is stored as a STRING (see _qa_record's str(category)), so
    # every comparison here must be against strings — comparing against ints
    # silently sent ALL categories to the multi-name `else` branch, producing
    # malformed options (e.g. Cat-4 "Is A B's father?" → ["Emily.","Mary.",
    # "None.","No.","Dorothy, No."] instead of Yes/No/Unknown).
    if cat in ("4", "5"):
        opts, idx = _mc_yes_no_unknown(ans, seed)
        letters = OPTION_LETTERS_3
    elif cat == "3":
        opts, idx = _mc_counting(ans, seed)
        letters = OPTION_LETTERS_5
    elif cat == "6":
        # forbid other valid names AND own name from appearing as distractors
        forbid = set(q.get("disambig_set", [])) | {q["person"]}
        opts, idx = _mc_name_single(ans, all_names, seed, forbid_in_options=forbid)
        letters = OPTION_LETTERS_5
    elif cat in ("1", "2") or ans == "None.":
        # single-answer name questions — forbid the asker's own name as a distractor
        if "," in ans:
            opts, idx = _mc_name_multi(ans, all_names, seed)
        else:
            opts, idx = _mc_name_single(ans, all_names, seed,
                                        forbid_in_options={q["person"]})
        letters = OPTION_LETTERS_5
    else:
        # 1m, 1w, 2m: multi-answer
        opts, idx = _mc_name_multi(ans, all_names, seed)
        letters = OPTION_LETTERS_5

    return {
        **q,
        "options": opts,
        "correct_idx": idx,
        "correct_letter": letters[idx],
        "n_options": len(opts),
        "mc_question": _format_mc(q["question"], opts, letters),
    }


def _format_mc(question: str, options: list[str], letters: str) -> str:
    lines = [question]
    for i, opt in enumerate(options):
        lines.append(f"{letters[i]}. {opt}")
    return "\n".join(lines)


def balance_letters(records: list[dict], seed: int) -> None:
    """Re-place the correct option so correct-letter is UNIFORM across slots.

    Without this the correct letter follows each question's per-question option
    shuffle → can be skewed and is not uniform. Here, within each n_options
    group, target slots are assigned round-robin (shuffled), so e.g. for
    5-option questions ~20% land on each of A-E. Mutates records in place:
    rewrites options / correct_idx / correct_letter / mc_question.
    """
    rng = random.Random(seed)
    by_n: dict[int, list[dict]] = {}
    for r in records:
        by_n.setdefault(r["n_options"], []).append(r)

    for n, group in by_n.items():
        letters = OPTION_LETTERS_3 if n == 3 else OPTION_LETTERS_5
        letters = letters[:n]
        # uniform target-slot sequence: full cycles of 0..n-1, shuffled
        targets = [i % n for i in range(len(group))]
        rng.shuffle(targets)
        for r, tgt in zip(group, targets):
            correct = r["options"][r["correct_idx"]]
            distractors = [o for i, o in enumerate(r["options"]) if i != r["correct_idx"]]
            rng.shuffle(distractors)
            new_opts = distractors[:tgt] + [correct] + distractors[tgt:]
            r["options"] = new_opts
            r["correct_idx"] = tgt
            r["correct_letter"] = letters[tgt]
            r["mc_question"] = _format_mc(r["question"], new_opts, letters)


def qa_to_mc_conversation(rec: dict) -> Conversation:
    return Conversation(
        system_prompt="",
        metadata={
            "category":        rec["category"],
            "rel":             rec["rel"],
            "person":          rec["person"],
            "hops":            rec.get("hops"),
            "options":         rec["options"],
            "correct_idx":     rec["correct_idx"],
            "correct_letter":  rec["correct_letter"],
            "n_options":       rec["n_options"],
            "original_answer": rec["answer"],
            "question_text":   rec["question"],
        },
        messages=[
            Conversation.Message(role="user",      content=rec["mc_question"],          token_ids=None, top_logprobs=None),
            Conversation.Message(role="assistant", content=f"{rec['correct_letter']}.", token_ids=None, top_logprobs=None),
        ],
    )


# ── Top-level pipeline ─────────────────────────────────────────────────────
def build_all_qa(tree: FamilyTree, lookup: dict, n_verif_per_rel: int, seed: int) -> list[dict]:
    rng = random.Random(seed)
    qa = []
    qa += gen_cat1_2_3(tree, lookup)
    qa += gen_cat4_verification(tree, lookup, rng, n_per_person_rel=n_verif_per_rel)
    qa += gen_cat5_existence(tree, lookup)
    qa += gen_cat6_disambig(tree, lookup)
    return qa


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tree",             type=str, default=None,
                    help="Path to family_tree.json (default: alongside this script)")
    ap.add_argument("--out-dir",          type=str, default=None,
                    help="Where to write parquets (default: dir of --tree)")
    ap.add_argument("--test-frac",        type=float, default=0.2)
    ap.add_argument("--split-mode",       choices=["person", "question"], default="question",
                    help="person=hold out whole people (structural generalization); "
                         "question=random hold-out of questions (default)")
    ap.add_argument("--seed",             type=int, default=42)
    ap.add_argument("--n-verif-per-rel",  type=int, default=12,
                    help="Cat-4 verification questions per (person, rel)")
    ap.add_argument("--rebalance",  dest="rebalance", action="store_true", default=True,
                    help="Downsample categories to MIX_DEFAULT target shares (default on)")
    ap.add_argument("--no-rebalance", dest="rebalance", action="store_false",
                    help="Keep all raw categories at natural counts (88%% verify+exist)")
    args = ap.parse_args()

    from examples.graph.paths import BASE_TREE_JSON
    tree_path = Path(args.tree) if args.tree else BASE_TREE_JSON
    out_dir = Path(args.out_dir) if args.out_dir else tree_path.parent
    out_dir.mkdir(parents=True, exist_ok=True)

    data = json.loads(tree_path.read_text())
    tree = FamilyTree(data)
    print(f"tree: {len(tree.people)} people")

    corpus_text = tree.to_text()
    (out_dir / "family_tree_corpus.txt").write_text(corpus_text)

    print("BFS relationship lookup …")
    lookup = build_rel_lookup(tree)

    qa = build_all_qa(tree, lookup, n_verif_per_rel=args.n_verif_per_rel, seed=args.seed)
    print(f"raw QA: {len(qa)}")
    if args.rebalance:
        qa = rebalance(qa, MIX_DEFAULT, seed=args.seed)
        print(f"rebalanced QA: {len(qa)} (MIX_DEFAULT target shares)")
    by_cat: dict = {}
    for q in qa:
        by_cat.setdefault(q["category"], 0)
        by_cat[q["category"]] += 1
    tot = len(qa)
    for k in sorted(by_cat, key=str):
        print(f"  cat {k:>3}: {by_cat[k]:5d}  ({by_cat[k]/tot:5.1%})")
    print(f"  ~per person: {len(qa) / len(tree.people):.1f}")

    if args.split_mode == "person":
        train_qa, test_qa, train_people, test_people = split_by_person(
            tree, qa, test_frac=args.test_frac, seed=args.seed,
        )
        print(f"split=person | train people ({len(train_people)}): {train_people}")
        print(f"              test  people ({len(test_people)}): {test_people}")
    else:
        train_qa, test_qa = split_by_question(
            qa, test_frac=args.test_frac, seed=args.seed,
        )
        train_people, test_people = None, None
        print(f"split=question | random hold-out of {args.test_frac:.0%} of questions")
    print(f"train QA: {len(train_qa)}  test QA: {len(test_qa)}")

    all_names = [p["name"] for p in tree.people]
    mc_train = [build_mc_record(q, all_names) for q in train_qa]
    mc_test  = [build_mc_record(q, all_names) for q in test_qa]
    # uniform correct-letter distribution within each split
    balance_letters(mc_train, seed=args.seed)
    balance_letters(mc_test,  seed=args.seed + 1)

    write_conversations([qa_to_mc_conversation(r) for r in mc_train], str(out_dir / "train_mc.parquet"))
    write_conversations([qa_to_mc_conversation(r) for r in mc_test],  str(out_dir / "test_mc.parquet"))
    (out_dir / "train_meta_mc.json").write_text(json.dumps(mc_train, indent=2))
    (out_dir / "test_meta_mc.json").write_text(json.dumps(mc_test,  indent=2))
    (out_dir / "split_meta.json").write_text(json.dumps({
        "split_mode":   args.split_mode,
        "train_people": train_people,   # null for split_mode=question
        "test_people":  test_people,    # null for split_mode=question
        "n_train_qa":   len(train_qa),
        "n_test_qa":    len(test_qa),
        "test_frac":    args.test_frac,
        "seed":         args.seed,
        "n_verif_per_rel": args.n_verif_per_rel,
    }, indent=2))
    print(f"→ {out_dir}/train_mc.parquet ({len(mc_train)})")
    print(f"→ {out_dir}/test_mc.parquet  ({len(mc_test)})")


if __name__ == "__main__":
    main()
